name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: ansible/ansible-lint-action@master
      name: Lint
      with:
        ACTION_PLAYBOOK_NAME: "wordpress-nginx/site.yml"
